

# Configure worker connection
events {}

# Everything related to http live here
http {

# This will create the logical backend. Instead of writing proxy_pass http://auth-service:8000; everywhere we use proxy_pass http://auth_service;
# Later, load balancing becomes as simple as:
# upstream auth_service {
#     server auth-service-1:8000;
#     server auth-service-2:8000;
#     server auth-service-3:8000;
 # }
    upstream auth_service {
        server auth-service:8000;
    }

    server {

        listen 80;

        location /api/v1/ {

            proxy_pass http://auth_service;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /docs {
            proxy_pass http://auth_service;
        }

        location /openapi.json {
            proxy_pass http://auth_service;
        }

        location /redoc {
            proxy_pass http://auth_service;
        }
    }
}

# What is NGINX?
# NGINX (pronounced as Engine-X) is a high performance web server and revers proxy. In a microservices architecture, it's most common role is to act as the entry point for all client requests.
# Think of it as front door of backend.

#                      Angular
#                          │
#                          ▼
#                  localhost:8080
#                          │
#                      NGINX Gateway
#                          │
#         ┌────────────────┼────────────────┐
#         │                │                │
#         ▼                ▼                ▼
#    Auth Service     User Service    Booking Service



# User
#  │
#  ▼
# Angular
#  │
#  │ POST /api/v1/auth/login
#  ▼
# NGINX
#  │
#  │ "This path starts with /api/v1/auth"
#  ▼
# Auth Service
#  │
#  │ Validate credentials
#  ▼
# MongoDB
#  │
#  │ User found
#  ▼
# Auth Service
#  │
#  │ Generate JWT
#  ▼
# NGINX
#  │
#  ▼
# Angular
#  │
#  ▼
# User Logged In

# NGINX should handle infrastructure concerns.

#                  NGINX
#                     │
#     ┌───────────────┼───────────────┐
#     │               │               │
#  Request Routing  SSL/TLS      Load Balancing
#  Logging          CORS         Compression
#  Rate Limiting   Reverse Proxy Security Headers